set -g mouse on
set -g default-terminal "tmux-256color"
set -g status-interval 1
set -g status-justify centre
set -g status-left-length 50
set -g status-right-length 150
set -sg escape-time 0
set -g history-limit 100000

